// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/projects.tsx";
import * as $6 from "./routes/x[name].tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/kofi-widget.jsx";
import * as $$2 from "./islands/snake.jsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/projects.tsx": $5,
    "./routes/x[name].tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/kofi-widget.jsx": $$1,
    "./islands/snake.jsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
